WerewolfDice/Controllers/WorldOfDarknessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WerewolfDice.Controllers
{
    public class WorldOfDarknessController : Controller
    {
        // GET: WorldOfDarkness
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Character(string id)
        {
            return View("~/Views/WorldOfDarkness/index.cshtml",model:id);
        }
    }
}

WerewolfDice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - World of Darkness</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)

</head>
<body class="container">
<div class="app-bar fixed-top" data-role="appbar">
    @Html.ActionLink("Werewolf Dice Roller", "Index", "Home", new {area = ""}, new {@class = "app-bar-element"})
    <ul class="app-bar-menu">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        <li>@Html.ActionLink("Die Roller", "Index", "WorldOfDarkness")</li>
        @Html.Partial("_LoginPartial")
    </ul>

</div>


<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - World of Darkness Die Roller.</p>
    </footer>
</div>

</body>
</html>